<!-- 
 This file is part of the TarSignup Module (https://github.com/xFran/TarSignup.git)
 
 @link      https://github.com/xFran/TarSignup.git for the canonical source repository
 @copyright Copyright (c) 2013 Francisc Tar (https://github.com/xFran/TarSignup.git)
 @license   http://framework.zend.com/license/new-bsd New BSD License
-->

<?php
$this->headTitle('Notice');
?>
<div id="content">
    <div id="content-header">
        <h3>Notice</h3>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <h5>Message send ...</h5>
            <div class="span10">
                <p>Check your e-mail and click on the hyperlink in order to activate your account. Thank You.</p>
                <a class="btn btn-primary" href="<?php echo $this->url('home') ?>">Back to Home</a>
            </div>
        </div>
    </div>
</div>