<!-- 
 This file is part of the TarSignup Module (https://github.com/xFran/TarSignup.git)
 
 @link      https://github.com/xFran/TarSignup.git for the canonical source repository
 @copyright Copyright (c) 2013 Francisc Tar (https://github.com/xFran/TarSignup.git)
 @license   http://framework.zend.com/license/new-bsd New BSD License
-->

<?php
$this->headTitle('Profile');
?>
<div id="content">
    <div id="content-header">
        <h3><?php echo $this->escapeHtml('User Profile ' . ucfirst($this->user)); ?></h3>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <?php if(!empty($this->scc)): ?>
                <div class="span10">
                    <ul>
                    <?php foreach ($this->scc as $v): ?>
                        <li><?php echo $v; ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <?php if(!empty($this->err)): ?>
                <div class="span10">
                    <ul>
                    <?php foreach ($this->err as $v): ?>
                        <li><?php echo $v; ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <div class="span10">
                <br />
                <a class="btn btn-primary" href="<?php echo $this->url('tar-signup', array('action'=>'logout')); ?>">Logout</a>
                <br />
            </div>
        </div>
    </div>
</div>